### ISSUE TITLE
As a maintainer I should document the design and functionality of the overall application

### ISSUE THREAD

**Issue by thescientist13** [ContributaryCommunity/contributary#3]
## Type of Change
- [ ] New Feature Request
- [x] Documentation
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

To move out of a POC phase, formal features and designs should be made, to best plan out the development.

One important UX consideration I can think of will be handling long lists, so pagination strategies and / or lazy loading strategies will be required, as well as potential text searching capabilities.

## Details

Topics to cover:
1. [ ] [Topology / API](https://github.com/ContributaryCommunity/contributary/issues/4) - How the data is managed, setup, etc
1. [ ] [Technical Architecture](https://github.com/ContributaryCommunity/contributary/issues/5) - server(less), API gateway, S3, etc.  the infrastructure and data organization
1. [ ] [Release Management](https://github.com/ContributaryCommunity/contributary/issues/6) - Release process and workflows
1. [ ] Designs: What the app should look like (this ticket)
1. [ ] [Functional Specification](https://github.com/ContributaryCommunity/contributary/issues/7): What the app should do
1. [ ] [Onboarding Guide](https://github.com/ContributaryCommunity/contributary/issues/8)
